networks:
  app_network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: golang:1.24.0
    ports:
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    networks:
      - app_network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - pg-gtexter-data:/var/lib/postgresql/data

volumes:
  pg-gtexter-data:
